### ISSUE TITLE
Application crashes if Cursor content is bigger than 1MB

### ISSUE THREAD

**Issue by neuromancer85** [sqlcipher/android-database-sqlcipher#47]
I know that this is a limit hard-coded in the CursorWindow implementation...
However I need to store a file in the encrypted db as a blob, but since it is bigger than 1mb I cannot retrive it without causing a crash... Is there a way to bypass this limitation? For example, is there a way to query the blob in chunks of max 1mb?

**Comment by developernotes** [comment]
Hello @neuromancer85,

I wanted to follow up with you regarding this report. Last week we released a new version of both SQLCipher and SQLCipher for Android. SQLCipher for Android included a fix that addresses the 1 MB limit previously reported. Please take a look when you have the opportunity. Thanks!

**Comment by ezengsvmx** [comment]
With cordova-sqlcipher-adapter 0.1.9-pre3 "Cordova sqlcipher adapter", I am still seeing this message below. Is this fix not included in 0.1.19?

E/CursorWindow: need to grow: mSize = 1048576, size = 1133544, freeSpace() = 1048409, numRows = 1
E/CursorWindow: Attempting to grow window beyond max size (1048576)
E/Cursor: Failed allocating 1133544 bytes for text/blob at 0,2

**Comment by developernotes** [comment]
Hi @ezengsvmx 

Are you referring to [this](https://github.com/litehelpers/Cordova-sqlcipher-adapter) project? If so, it is not a project we developed or maintain.

**Comment by ezengsvmx** [comment]
Thanks for the reply. Yes. However, it is based on sqlcipher 3.4.1 though.
